### ISSUE TITLE
proposal: build complex objects from more than one config value

### ISSUE THREAD

**Issue by wuan** [TNG/config-builder#25]
The idea (thanks to @wolfs) is to enable creating complex transformers which can use more than one input, e.g. using the hierarchy of the property name:

Property-File content:

```
connection.a.host
connection.a.port
connection.a.user
connection.a.password
```

Java Config Class:

```
@ImportedValue('connection.a')
@TypeTransformers('MapToComplexObjectTransformer.class})
private ComplexObject connection;
```

**Comment by knaufk** [comment]
I was just thinking about this feature, as we would like to use it in our project. Was there any progress on this since 2014?

**Comment by wuan** [comment]
So far this is still in proposal state, your contribution and/or further discussion is welcome.

**Comment by knaufk** [comment]
Maybe we just have a quick talk on Friday/Saturday ;)

There are basically two features I am thinking about (and interested in contributing). The first one is simpler (I am not even sure, that this is not possible right now.):

Property-File Content:
```
metrics.<metrics_name_1>=
metrics.<metrics_name_2>=
```

Java Config Class: 

```
@PropertyValuePrefix('metrics')
private Map<String, String> metrics;
```
The keys of metrics would be `<metrics_name_1>` and `<metrics_name_2>`. The values the corresponding property values. 

The second is basically your example above.

**Comment by theone1984** [comment]
At the moment, this issue is out of scope
